apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: netflix-app
    namespace: argocd
spec:
    project: default
    source:
        repoURL: 'https://github.com/amitvashisttech/kubernetes-eks-bs-28-Feb-2024.git'
        path: 38-Netflix-Project/manifests/
        targetRevision: main
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: default

