apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-env
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: amitvashist7/k8s-tiny-web
        imagePullPolicy: IfNotPresent
        ports:
        - name: nodejs-port
          containerPort: 80
        env: 
        - name: MY_USERNAME
          valueFrom: 
            secretKeyRef:
              name: mysecrets
              key: username.txt 
        - name: MY_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysecrets
              key: password.txt 
