apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-nginx
  name: hello-nginx
spec:
  containers:
  - image: nginx:1.11
    name: hello-nginx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
