apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hpa-example  
  template:
    metadata:
      labels:
        app: hpa-example
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: hpa-example
        image: amitvashist7/hpa-example
        ports:
        - name: http-port
          containerPort: 80
        resources:
          requests:
            cpu: 100m
