apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-tc
  labels:
    app: red-tc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: red-tc
  template:
    metadata:
      labels:
        app: red-tc
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: k8s-demo
        image: amitvashist7/k8s-tiny-web
        imagePullPolicy: IfNotPresent
        ports:
        - name: node-port
          containerPort: 80
      tolerations:
      - key: "team"
        operator: "Equal"
        value: "red"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: team
                operator: In
                values:
                - red
