apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
    version: v2
  name: hello-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
      version: v2
  template:
    metadata:
      labels:
        app: hello
        version: v2
    spec:
      containers:
      - name: hello
        image: amitvashist7/http-echo
        env: 
        - name: TEXT 
          value: hello, this is v2
        - name: NEXT
          value: "world:8080"
        ports:
        - name: http
          containerPort: 8080
