apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: index-gen
  template:
    metadata:
      labels:
        app: index-gen
    spec:
      containers:
      - name: upload-index
        image: amazon/aws-cli
        command: ["sh", "-c", "'while true; do date >> /mnt/index.html; hostname >> /mnt/index.html;echo "###### Welcome to NFS PV Storage ######">> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'; aws s3 cp /mnt/index.html s3://test-bucket-1-eks/index.html"]
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret-key
